# Importing Library

In [1]:
import numpy as np

# Partitioning the address byte

In [32]:
def partition(i):
    b_offset = int("{:02d}".format(i%100))
    b_no = int(i / 100)
    tag = int(b_no / 100)
    line_no = int("{:02d}".format(b_no%100))
    return tag, line_no, b_no, b_offset

# Initial Condiitons

In [33]:
cache = [np.array([int, np.empty(4), 0], dtype=object), 
         np.array([int, np.empty(4), 0], dtype=object), 
         np.array([int, np.empty(4), 0], dtype=object), 
         np.array([int, np.empty(4), 0], dtype=object)] 
mem = [[0]*4 for x in range(32)]

In [34]:
direct_hash = [[] for x in range(4)]
direct_map = {}
for i in range(32):
    direct_map[i] = i % 4

for i in direct_map:
    direct_hash[direct_map[i]].append(i)

direct_hash

[[0, 4, 8, 12, 16, 20, 24, 28],
 [1, 5, 9, 13, 17, 21, 25, 29],
 [2, 6, 10, 14, 18, 22, 26, 30],
 [3, 7, 11, 15, 19, 23, 27, 31]]

# Check Cache

In [47]:
def check_cache(tag, line_no, b_offset):
    valid = 0
    
    required_bno = direct_hash[line_no][tag]
    
    if(cache[line_no][0] == required_bno): #hit
        valid = 1
        print(f"Data: {cache[line_no][1][b_offset]}")
    else: #Miss
        valid = 0
        print(f"Data: {mem[required_bno][b_offset]}")
        cache[line_no][0] = required_bno
        cache[line_no][1] = mem[required_bno]
        
            
    return int(valid)

# Main

In [ ]:
while(1):
    print("Enter 1 for read, 0 for write and q to exit: ")
    temp = input()
    if(temp == 'q'): # Quit Condition
        break
    else:
        rw = int(temp)
        print("Enter memory address: ")
        i = int(input())
        
        tag, line_number, block_number, block_offset = partition(i)
        
        block_number = int(str(block_number), 2)
        block_offset = int(str(block_offset), 2)
        line_number = int(str(line_number), 2)
        tag = int(str(tag), 2)
        
        print(f"block_number: {block_number}")
        print(f"block_offset: {block_offset}")
        print(f"line_number: {line_number}")
        print(f"tag: {tag}")
        
        if(rw): # Read Operation
            hit = check_cache(tag, line_number, block_offset)
            print(f"Hit/Miss: {hit}")
    
        else: # Write Operation
            print("Enter data: ")
            data = int(input())
            mem[block_number][block_offset] = data

Enter 1 for read, 0 for write and q to exit: 


 1


Enter memory address: 


 0000011


block_number: 0
block_offset: 3
line_number: 0
tag: 0
Data: 42
Hit/Miss: 0
Enter 1 for read, 0 for write and q to exit: 


# Debug

In [48]:
mem

[[0, 0, 0, 42],
 [420, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [1977, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]

In [46]:
cache

[array([4, list([1977, 0, 0, 0]), 0], dtype=object),
 array([<class 'int'>,
        array([-3.10503618e+231, -3.10503618e+231,  1.97626258e-323,
         0.00000000e+000]),
        0], dtype=object),
 array([<class 'int'>,
        array([-3.10503618e+231, -3.10503618e+231, -3.10503618e+231,
        -3.10503618e+231]),
        0], dtype=object),
 array([<class 'int'>,
        array([-3.10503618e+231, -3.10503618e+231,  3.45845952e-323,
         0.00000000e+000]),
        0], dtype=object)]